- name: Install Apache
  apt:
    pkg=apache2

- name: Enable Apache modules
  file:
    dest="{{ item.dest }}"
    src="{{ item.src }}"
    state=link
  with_items:
    - { dest: "/etc/apache2/mods-enabled/proxy.load", src: "../mods-available/proxy.load" }
    - { dest: "/etc/apache2/mods-enabled/proxy.conf", src: "../mods-available/proxy.conf" }
    - { dest: "/etc/apache2/mods-enabled/proxy_fcgi.load", src: "../mods-available/proxy_fcgi.load" }
    - { dest: "/etc/apache2/mods-enabled/proxy_http.load", src: "../mods-available/proxy_http.load" }
    - { dest: "/etc/apache2/mods-enabled/proxy_wstunnel.load", src: "../mods-available/proxy_wstunnel.load" }
    - { dest: "/etc/apache2/mods-enabled/rewrite.load", src: "../mods-available/rewrite.load" }
  notify:
    Restart Apache

- name: Add Apache to group php
  user: name=www-data
        groups=php
  notify:
    Restart Apache

- name: Remove default site
  file:
    path="{{ item }}"
    state=absent
  with_items:
    - /etc/apache2/sites-enabled/000-default.conf
    - /etc/apache2/sites-available/000-default.conf
    - /var/www/html
  notify:
    Restart Apache

- name: Add default sites
  copy:
    src="{{ item.src }}"
    dest="{{ item.dest }}"
    owner=root
    group=root
    mode=0644
  with_items:
    - { src: default-vhost-php.conf, dest: /etc/apache2/sites-available/001-default-vhost-php.conf }
    - { src: default-vhost-hhvm.conf, dest: /etc/apache2/sites-available/002-default-vhost-hhvm.conf }
  notify:
    Restart Apache

- name: Enable default sites
  file:
    src="{{ item.src }}"
    dest="{{ item.dest }}"
    state=link
  with_items:
    - { src: ../sites-available/001-default-vhost-php.conf, dest: /etc/apache2/sites-enabled/001-default-vhost-php.conf }
    - { src: ../sites-available/002-default-vhost-hhvm.conf, dest: /etc/apache2/sites-enabled/002-default-vhost-hhvm.conf }
  notify:
    Restart Apache

- name: Enable Apache service
  service:
    name=apache2
    state=started
    enabled=yes
